/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define MESSAGEPROG ((rpc_uint)0x20000001)
#define PRINTMESSAGEVERS ((rpc_uint)1)

#ifdef __cplusplus
#define PRINTMESSAGE ((rpc_uint)1)
extern "C" int * printmessage_1(char **, CLIENT *);
extern "C" int * printmessage_1_svc(char **, struct svc_req *);

#elif __STDC__
#define PRINTMESSAGE ((rpc_uint)1)
extern  int * printmessage_1(char **, CLIENT *);
extern  int * printmessage_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define PRINTMESSAGE ((rpc_uint)1)
extern  int * printmessage_1();
extern  int * printmessage_1_svc();
#endif /* Old Style C */

#endif /* !_MSG_H_RPCGEN */
